try:
    list1 = [1,2,3]
    print(list1[4])

except Exception as e:
    print(e)